### ISSUE TITLE
Support more cool robots

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-playground#1]
Test or evaluate the following robots (features, cost, etc) to be included in Robot Devastation:
- [Loki (omnidirectional robot)](https://github.com/davidsanfal/loki)
- [miniKame (cute quadrupted robot)](https://github.com/JavierIH/miniKame)
- [Mizu (quadruped robot)](https://github.com/bqlabs/mizu)

**Comment by jgvictores** [comment]
All documented at https://github.com/asrob-uc3m/robotDevastation-playground/blob/develop/README.md#support-more-cool-robots (perma: https://github.com/asrob-uc3m/robotDevastation-playground/blob/4718f6a57d8e2fa5c273bfb42cfa4d86d2b9c4a7/README.md#support-more-cool-robots)
