### ISSUE TITLE
Think about Game Engines

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-playground#2]
Test or evaluate the following Game Engines to be included in Robot Devastation:
- [ ] [Unity](http://www.unity3d.com/)
- [ ] [Unreal](https://www.unrealengine.com/)
- [ ] [Ogre](http://www.ogre3d.org/)
- [ ] [Irrlicht](http://irrlicht.sourceforge.net/)
- [ ] [Crystal Space](http://www.crystalspace3d.org/main/Main_Page)
- [ ] [Panda3D](https://github.com/panda3d/panda3d)

**Comment by David-Estevez** [comment]
Unreal Engine 4 Editor works without problem in my Linux Mint PC and the examples included by default are very cool, but @jgvictores is concerned about the license. We would need to investigate on how to make Robot Devastation + Game Engine as libre as possible.

Also, I have found this plugin which looks very promising to view streams on a game: https://github.com/ufna/VaQuoleUI

**Comment by jgvictores** [comment]
Have been checking https://github.com/ioquake/ioq3 (GPL). Compiling doesn't seem very user-friendly, and haven't seen many developer tools either (as compared to other Game Engines).

**Comment by jgvictores** [comment]
Added pygame and closing with list at https://github.com/asrob-uc3m/robotDevastation-playground#research-about-game-engines (perma: https://github.com/asrob-uc3m/robotDevastation-playground/tree/a81ffbc74a4bf8efdedcec97d708e6189813759a#research-about-game-engines)
