### ISSUE TITLE
Think about Android version

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-playground#4]
Think about Android version

*  [Android version of Robot Devastation (just an old idea).](http://asrob.uc3m.es/index.php/ANDROID)

**Comment by PeterBowman** [comment]
Useful links found by @jgvictores:

* https://github.com/ZBar/ZBar/tree/master/android
* https://wiki.libsdl.org/Android

By having those two and [YARP for Android](https://alecive.github.io/research/2015/08/01/yarpdroid/) to cover all RD dependencies, I wonder if the game could be ported to Android with "nothing more" than a CMake cross-compile switch.

See `BUILD_ANDROID` at https://github.com/robotology/yarp/compare/master...robotology-playground:yarp-android. In case the branch gets deleted: https://github.com/robotology-playground/yarp/commit/fd5eece5d7a378d19b6d78eec45dd97a9e033b00 + https://github.com/robotology-playground/yarp/commit/f47e9996d6e077f8114aa066233c87c047e0f5bb.

**Comment by jgvictores** [comment]
More Android-oriented resources:
- https://www.tensorflow.org/lite
- https://developers.google.com/ar/discover/

**Comment by jgvictores** [comment]
Resources added at https://github.com/asrob-uc3m/robotDevastation-playground/commit/0f17447309c2a421214852c3b0e94e8351349ff4

**Comment by jgvictores** [comment]
On a `termux`:
```diff
diff --git a/src/libYARP_OS/src/PortCore.cpp b/src/libYARP_OS/src/PortCore.cpp
index 064fa2d27..80f7549bb 100644
--- a/src/libYARP_OS/src/PortCore.cpp
+++ b/src/libYARP_OS/src/PortCore.cpp
@@ -2587,7 +2587,7 @@ bool PortCore::setProcessSchedulingParam(int priority, int policy) {
 #if defined(__linux__)
     // set the sched properties of all threads within the process
     struct sched_param sch_param;
-    sch_param.__sched_priority = priority;
+    sch_param.sched_priority = priority;

     DIR *dir;
     char path[PATH_MAX];
diff --git a/src/libYARP_OS/src/SystemInfo.cpp b/src/libYARP_OS/src/SystemInfo.cpp
index 1ad3fd41a..6ce6fd632 100644
--- a/src/libYARP_OS/src/SystemInfo.cpp
+++ b/src/libYARP_OS/src/SystemInfo.cpp
@@ -803,7 +803,7 @@ SystemInfo::ProcessInfo SystemInfo::getProcessInfo(int pid) {
     // scheduling params
     struct sched_param param;
     if ( sched_getparam(pid, &param) == 0 )
-        info.schedPriority = param.__sched_priority;
+        info.schedPriority = param.sched_priority;
     info.schedPolicy = sched_getscheduler(pid);

 #elif defined(_WIN32)
diff --git a/src/libYARP_OS/src/ThreadImpl.cpp b/src/libYARP_OS/src/ThreadImpl.cpp
index a1d4df306..9524ea766 100644
--- a/src/libYARP_OS/src/ThreadImpl.cpp
+++ b/src/libYARP_OS/src/ThreadImpl.cpp
@@ -523,7 +523,7 @@ void ThreadImpl::yield()
 #elif defined(YARP_HAS_ACE) // Use ACE API
     ACE_Thread::yield();
 #elif defined(__unix__) // Use the POSIX syscalls
-    pthread_yield();
+    sched_yield();
 #else
     YARP_ERROR(Logger::get(), "Cannot yield thread without ACE");
 #endif
```
